import Head from 'next/head';
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub
} from 'react-icons/ai';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { useState } from "react";
import deved from '../public/dev-ed-wave.png';
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Fabio Migliaccio Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900" >
        <section className="min-h-screen" >
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="font-burtons text-xl  dark:text-white"  > Developedbyed</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-blue-500  text-white px-4  py-2 rounded-md ml-8' href="#"> Resume </a> </li>
            </ul>
          </nav>
          <div className='text-center p-10 '>
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">Fabio Migliaccio</h2>
            <h3 className='text-2xl py-3 md:text-3xl dark:text-white' >Full stack developer</h3>
            <p className='text-md py-5 leading-8 text-gray-800  md:text-xl max-w-xl mx-auto dark:text-white'>
              I am a confident, responsible and Goal-oriented
              with excellent problem-solving skills. <br></br>
              Looking forward to share my knowledges and abilities in optimizing web
              functionalities in a challenging and motivating work environment. 
               </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <AiFillTwitterCircle />
            <a href='https://www.linkedin.com/in/fabio-migliaccio-6a7124180/' target="blank"> <AiFillLinkedin /> </a>
            <a href='https://github.com/FabioMigliacc' target="blank"> <AiFillGithub /> </a>

          </div>
          <div>
            <div className='mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mb-8 mt-20 md:h-96 md:w-96'>
              <Image src={deved} alt="3d" layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>

        {/* SERVICES I OFFER SECTION */}
        <section>
          <div>

            <h3 className='text-3xl py-2  dark:text-white' > Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a
              developer, I have attended two coding bootcamps focused on front-end 
              and back-end development. <br></br>
              
            
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Thanks to this year of experience I have developed the following skills : 
               
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} alt="img" width={100} height={100} className='mx-auto' />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Front-End developer
              </h3>
              <p className="py-2">
              Developing new user-facing features, determining the structure and design 
              of web pages, building reusable codes.
              </p>
              <h4 className="py-4 text-teal-600">Technologies I use</h4>
              <p className="text-gray-800 py-1">HTML5</p>
              <p className="text-gray-800 py-1">CSS3</p>
              <p className="text-gray-800 py-1">TailwindCSS</p>
              <p className="text-gray-800 py-1">React</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} alt="img" width={100} height={100} className='mx-auto' />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Back-end developer
              </h3>
              <p className="py-2">
              Create, code, and improve the server-side app, and databases 
              to create a functional experience for the end-user.
              </p>
              <h4 className="py-4 text-teal-600">Back-end Tools I Use</h4>
              <p className="text-gray-800 py-1">NodeJs</p>
              <p className="text-gray-800 py-1">Express</p>
              <p className="text-gray-800 py-1">MongoDB</p>
              <p className="text-gray-800 py-1">Javascript/Typescript</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} alt="img" width={100} height={100} className='mx-auto' />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Team work</h3>
              <p className="py-2">
               In the current bootcamp  I have worked in projects with my 
               classmates and became a great team worker.
              </p>
              <h4 className="py-4 text-teal-600">Strong team work skills:</h4>
              <p className="text-gray-800 py-1">Listening</p>
              <p className="text-gray-800 py-1">Organizing</p>
              <p className="text-gray-800 py-1">Supportive</p>
              <p className="text-gray-800 py-1">Proactive</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-2  dark:text-white'> Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I have done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image
                alt="web1"
                src={web1}
                className='rounded-lg object-cover'
                width={'100%'}
                height={'100%'}
                layout='responsive' /></div>
            <div className='basis-1/3 flex-1'>
              <Image
                alt="web2"
                src={web2}
                className='rounded-lg object-cover'
                width={'100%'}
                height={'100%'}
                layout='responsive' /></div>
            <div className='basis-1/3 flex-1'>
              <Image
                alt="web3"
                src={web3}
                className='rounded-lg object-cover'
                width={'100%'}
                height={'100%'}
                layout='responsive' /></div>
            <div className='basis-1/3 flex-1'>
              <Image
                alt="web4"
                src={web4}
                className='rounded-lg object-cover'
                width={'100%'}
                height={'100%'}
                layout='responsive' /></div>
            <div className='basis-1/3 flex-1'>
              <Image
                alt="web5"
                src={web5}
                className='rounded-lg object-cover'
                width={'100%'}
                height={'100%'}
                layout='responsive' /></div>
            <div className='basis-1/3 flex-1'>
              <Image
                alt="web6"
                src={web6}
                className='rounded-lg object-cover'
                width={'100%'}
                height={'100%'}
                layout='responsive' /></div>
          </div>
        </section>
        <section>
          <h3 className='text-3xl py-2  dark:text-white'> Contact me: </h3>
          <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            E-mail: febbio9@gmail.com
          </p>
          <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Mobile phone : +34 634203739
          </p>
        </section>
        <footer className='text-center mx-auto bg-gradient-to-b from-teal-500 '>
          <p className=" text-md py-2  text-gray-800 dark:text-gray-200">
            © 2023 Fabio Migliaccio
          </p>
          <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            All right reserved
          </p>
        </footer>
      </main>
    </div>
  );
}
